name: CI

on: [push]
    
jobs:
    echo-hello:
        runs-on: ubuntu-slim
        steps:
            - name: say hello
              run: echo "hello world"

    echo-goodbye:
        runs-on: ubuntu-slim
        steps:
            - name: failed step
              run: |
                 echo "I will fail"
                 exit 0

            - name: say goodbye
              run: echo "goodbye world"


