name : windows-runner
on: [push]

jobs:
    echo-windows-runner:
        runs-on: windows-latest
        steps: 
            - name: windows os runner
              shell: bash
              run: echo "OS of this runner is $RUNNER_OS"
